spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:paymentssmdb
  flyway:
    enabled: false
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    active: local,clean
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
